name: Build STAGING Kernel

on:
  push:
    branches:
      - fuse-staging
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Compile
      run: |
        export TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
        ./build.sh
